linters:
  enable-all: true
  disable:
  - depguard
  - exhaustruct
  - funlen
  - gochecknoglobals
  - godot
  - nlreturn
  - promlinter
  - varnamelen
  - wsl

  # deprecated
  - deadcode
  - exhaustivestruct
  - golint
  - ifshort
  - interfacer
  - maligned
  - nosnakecase
  - scopelint
  - structcheck
  - varcheck
