linters:
  enable-all: true
  disable:
  - depguard
  - exhaustruct
  - nlreturn
  - varnamelen
  - wsl

  # deprecated
  - deadcode
  - exhaustivestruct
  - golint
  - ifshort
  - interfacer
  - maligned
  - nosnakecase
  - scopelint
  - structcheck
  - varcheck

linters-settings:
  gocritic:
    enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style
  gofumpt:
    extra-rules: true
  govet:
    check-shadowing: true
    enable-all: true
