// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/grpc/v1/client.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionType int32

const (
	SubscriptionType_HEARTBEAT SubscriptionType = 0
	SubscriptionType_METRICS   SubscriptionType = 1
)

// Enum value maps for SubscriptionType.
var (
	SubscriptionType_name = map[int32]string{
		0: "HEARTBEAT",
		1: "METRICS",
	}
	SubscriptionType_value = map[string]int32{
		"HEARTBEAT": 0,
		"METRICS":   1,
	}
)

func (x SubscriptionType) Enum() *SubscriptionType {
	p := new(SubscriptionType)
	*p = x
	return p
}

func (x SubscriptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_grpc_v1_client_proto_enumTypes[0].Descriptor()
}

func (SubscriptionType) Type() protoreflect.EnumType {
	return &file_proto_grpc_v1_client_proto_enumTypes[0]
}

func (x SubscriptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionType.Descriptor instead.
func (SubscriptionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_grpc_v1_client_proto_rawDescGZIP(), []int{0}
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SubscriptionType       `protobuf:"varint,1,opt,name=type,proto3,enum=proto.grpc.v1.SubscriptionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_proto_grpc_v1_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_v1_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_proto_grpc_v1_client_proto_rawDescGZIP(), []int{0}
}

func (x *Subscribe) GetType() SubscriptionType {
	if x != nil {
		return x.Type
	}
	return SubscriptionType_HEARTBEAT
}

type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SubscriptionType       `protobuf:"varint,1,opt,name=type,proto3,enum=proto.grpc.v1.SubscriptionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_proto_grpc_v1_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_v1_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_proto_grpc_v1_client_proto_rawDescGZIP(), []int{1}
}

func (x *Unsubscribe) GetType() SubscriptionType {
	if x != nil {
		return x.Type
	}
	return SubscriptionType_HEARTBEAT
}

var File_proto_grpc_v1_client_proto protoreflect.FileDescriptor

const file_proto_grpc_v1_client_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/grpc/v1/client.proto\x12\rproto.grpc.v1\"@\n" +
	"\tSubscribe\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.proto.grpc.v1.SubscriptionTypeR\x04type\"B\n" +
	"\vUnsubscribe\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.proto.grpc.v1.SubscriptionTypeR\x04type*.\n" +
	"\x10SubscriptionType\x12\r\n" +
	"\tHEARTBEAT\x10\x00\x12\v\n" +
	"\aMETRICS\x10\x01B(Z&github.com/tyholling/golang/proto/grpcb\x06proto3"

var (
	file_proto_grpc_v1_client_proto_rawDescOnce sync.Once
	file_proto_grpc_v1_client_proto_rawDescData []byte
)

func file_proto_grpc_v1_client_proto_rawDescGZIP() []byte {
	file_proto_grpc_v1_client_proto_rawDescOnce.Do(func() {
		file_proto_grpc_v1_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpc_v1_client_proto_rawDesc), len(file_proto_grpc_v1_client_proto_rawDesc)))
	})
	return file_proto_grpc_v1_client_proto_rawDescData
}

var file_proto_grpc_v1_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_grpc_v1_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_grpc_v1_client_proto_goTypes = []any{
	(SubscriptionType)(0), // 0: proto.grpc.v1.SubscriptionType
	(*Subscribe)(nil),     // 1: proto.grpc.v1.Subscribe
	(*Unsubscribe)(nil),   // 2: proto.grpc.v1.Unsubscribe
}
var file_proto_grpc_v1_client_proto_depIdxs = []int32{
	0, // 0: proto.grpc.v1.Subscribe.type:type_name -> proto.grpc.v1.SubscriptionType
	0, // 1: proto.grpc.v1.Unsubscribe.type:type_name -> proto.grpc.v1.SubscriptionType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_grpc_v1_client_proto_init() }
func file_proto_grpc_v1_client_proto_init() {
	if File_proto_grpc_v1_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpc_v1_client_proto_rawDesc), len(file_proto_grpc_v1_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_grpc_v1_client_proto_goTypes,
		DependencyIndexes: file_proto_grpc_v1_client_proto_depIdxs,
		EnumInfos:         file_proto_grpc_v1_client_proto_enumTypes,
		MessageInfos:      file_proto_grpc_v1_client_proto_msgTypes,
	}.Build()
	File_proto_grpc_v1_client_proto = out.File
	file_proto_grpc_v1_client_proto_goTypes = nil
	file_proto_grpc_v1_client_proto_depIdxs = nil
}
