// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/grpc/v1/connection.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *anypb.Any             `protobuf:"bytes,1,opt,name=request,proto3,oneof" json:"request,omitempty"`
	Response      *anypb.Any             `protobuf:"bytes,2,opt,name=response,proto3,oneof" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_grpc_v1_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_v1_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_v1_connection_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetRequest() *anypb.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ConnectRequest) GetResponse() *anypb.Any {
	if x != nil {
		return x.Response
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *anypb.Any             `protobuf:"bytes,1,opt,name=request,proto3,oneof" json:"request,omitempty"`
	Response      *anypb.Any             `protobuf:"bytes,2,opt,name=response,proto3,oneof" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_proto_grpc_v1_connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_v1_connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_v1_connection_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetRequest() *anypb.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ConnectResponse) GetResponse() *anypb.Any {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_proto_grpc_v1_connection_proto protoreflect.FileDescriptor

const file_proto_grpc_v1_connection_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/grpc/v1/connection.proto\x12\rproto.grpc.v1\x1a\x19google/protobuf/any.proto\"\x95\x01\n" +
	"\x0eConnectRequest\x123\n" +
	"\arequest\x18\x01 \x01(\v2\x14.google.protobuf.AnyH\x00R\arequest\x88\x01\x01\x125\n" +
	"\bresponse\x18\x02 \x01(\v2\x14.google.protobuf.AnyH\x01R\bresponse\x88\x01\x01B\n" +
	"\n" +
	"\b_requestB\v\n" +
	"\t_response\"\x96\x01\n" +
	"\x0fConnectResponse\x123\n" +
	"\arequest\x18\x01 \x01(\v2\x14.google.protobuf.AnyH\x00R\arequest\x88\x01\x01\x125\n" +
	"\bresponse\x18\x02 \x01(\v2\x14.google.protobuf.AnyH\x01R\bresponse\x88\x01\x01B\n" +
	"\n" +
	"\b_requestB\v\n" +
	"\t_response2a\n" +
	"\x11ConnectionService\x12L\n" +
	"\aConnect\x12\x1d.proto.grpc.v1.ConnectRequest\x1a\x1e.proto.grpc.v1.ConnectResponse(\x010\x01B(Z&github.com/tyholling/golang/proto/grpcb\x06proto3"

var (
	file_proto_grpc_v1_connection_proto_rawDescOnce sync.Once
	file_proto_grpc_v1_connection_proto_rawDescData []byte
)

func file_proto_grpc_v1_connection_proto_rawDescGZIP() []byte {
	file_proto_grpc_v1_connection_proto_rawDescOnce.Do(func() {
		file_proto_grpc_v1_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpc_v1_connection_proto_rawDesc), len(file_proto_grpc_v1_connection_proto_rawDesc)))
	})
	return file_proto_grpc_v1_connection_proto_rawDescData
}

var file_proto_grpc_v1_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_grpc_v1_connection_proto_goTypes = []any{
	(*ConnectRequest)(nil),  // 0: proto.grpc.v1.ConnectRequest
	(*ConnectResponse)(nil), // 1: proto.grpc.v1.ConnectResponse
	(*anypb.Any)(nil),       // 2: google.protobuf.Any
}
var file_proto_grpc_v1_connection_proto_depIdxs = []int32{
	2, // 0: proto.grpc.v1.ConnectRequest.request:type_name -> google.protobuf.Any
	2, // 1: proto.grpc.v1.ConnectRequest.response:type_name -> google.protobuf.Any
	2, // 2: proto.grpc.v1.ConnectResponse.request:type_name -> google.protobuf.Any
	2, // 3: proto.grpc.v1.ConnectResponse.response:type_name -> google.protobuf.Any
	0, // 4: proto.grpc.v1.ConnectionService.Connect:input_type -> proto.grpc.v1.ConnectRequest
	1, // 5: proto.grpc.v1.ConnectionService.Connect:output_type -> proto.grpc.v1.ConnectResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_grpc_v1_connection_proto_init() }
func file_proto_grpc_v1_connection_proto_init() {
	if File_proto_grpc_v1_connection_proto != nil {
		return
	}
	file_proto_grpc_v1_connection_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_grpc_v1_connection_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpc_v1_connection_proto_rawDesc), len(file_proto_grpc_v1_connection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpc_v1_connection_proto_goTypes,
		DependencyIndexes: file_proto_grpc_v1_connection_proto_depIdxs,
		MessageInfos:      file_proto_grpc_v1_connection_proto_msgTypes,
	}.Build()
	File_proto_grpc_v1_connection_proto = out.File
	file_proto_grpc_v1_connection_proto_goTypes = nil
	file_proto_grpc_v1_connection_proto_depIdxs = nil
}
