// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/grpc/v1/server.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_grpc_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_grpc_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           float64                `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        float64                `protobuf:"fixed64,2,opt,name=memory,proto3" json:"memory,omitempty"`
	BytesIn       uint64                 `protobuf:"varint,3,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut      uint64                 `protobuf:"varint,4,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	ErrorsIn      uint64                 `protobuf:"varint,5,opt,name=errors_in,json=errorsIn,proto3" json:"errors_in,omitempty"`
	ErrorsOut     uint64                 `protobuf:"varint,6,opt,name=errors_out,json=errorsOut,proto3" json:"errors_out,omitempty"`
	DiscardsIn    uint64                 `protobuf:"varint,7,opt,name=discards_in,json=discardsIn,proto3" json:"discards_in,omitempty"`
	DiscardsOut   uint64                 `protobuf:"varint,8,opt,name=discards_out,json=discardsOut,proto3" json:"discards_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_proto_grpc_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_proto_grpc_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *Metrics) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Metrics) GetMemory() float64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Metrics) GetBytesIn() uint64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *Metrics) GetBytesOut() uint64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *Metrics) GetErrorsIn() uint64 {
	if x != nil {
		return x.ErrorsIn
	}
	return 0
}

func (x *Metrics) GetErrorsOut() uint64 {
	if x != nil {
		return x.ErrorsOut
	}
	return 0
}

func (x *Metrics) GetDiscardsIn() uint64 {
	if x != nil {
		return x.DiscardsIn
	}
	return 0
}

func (x *Metrics) GetDiscardsOut() uint64 {
	if x != nil {
		return x.DiscardsOut
	}
	return 0
}

var File_proto_grpc_v1_server_proto protoreflect.FileDescriptor

const file_proto_grpc_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/grpc/v1/server.proto\x12\rproto.grpc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\tHeartbeat\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xeb\x01\n" +
	"\aMetrics\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x01R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x01R\x06memory\x12\x19\n" +
	"\bbytes_in\x18\x03 \x01(\x04R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x04 \x01(\x04R\bbytesOut\x12\x1b\n" +
	"\terrors_in\x18\x05 \x01(\x04R\berrorsIn\x12\x1d\n" +
	"\n" +
	"errors_out\x18\x06 \x01(\x04R\terrorsOut\x12\x1f\n" +
	"\vdiscards_in\x18\a \x01(\x04R\n" +
	"discardsIn\x12!\n" +
	"\fdiscards_out\x18\b \x01(\x04R\vdiscardsOutB(Z&github.com/tyholling/golang/proto/grpcb\x06proto3"

var (
	file_proto_grpc_v1_server_proto_rawDescOnce sync.Once
	file_proto_grpc_v1_server_proto_rawDescData []byte
)

func file_proto_grpc_v1_server_proto_rawDescGZIP() []byte {
	file_proto_grpc_v1_server_proto_rawDescOnce.Do(func() {
		file_proto_grpc_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpc_v1_server_proto_rawDesc), len(file_proto_grpc_v1_server_proto_rawDesc)))
	})
	return file_proto_grpc_v1_server_proto_rawDescData
}

var file_proto_grpc_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_grpc_v1_server_proto_goTypes = []any{
	(*Heartbeat)(nil),             // 0: proto.grpc.v1.Heartbeat
	(*Metrics)(nil),               // 1: proto.grpc.v1.Metrics
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_grpc_v1_server_proto_depIdxs = []int32{
	2, // 0: proto.grpc.v1.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_grpc_v1_server_proto_init() }
func file_proto_grpc_v1_server_proto_init() {
	if File_proto_grpc_v1_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpc_v1_server_proto_rawDesc), len(file_proto_grpc_v1_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_grpc_v1_server_proto_goTypes,
		DependencyIndexes: file_proto_grpc_v1_server_proto_depIdxs,
		MessageInfos:      file_proto_grpc_v1_server_proto_msgTypes,
	}.Build()
	File_proto_grpc_v1_server_proto = out.File
	file_proto_grpc_v1_server_proto_goTypes = nil
	file_proto_grpc_v1_server_proto_depIdxs = nil
}
