server:
  prefixURL: /prometheus
  baseURL: http://192.168.64.100/prometheus
  persistentVolume:
    enabled: false

serverFiles:
  prometheus.yml:
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - server-http:8080

alertmanager:
  enabled: false
