apiVersion: v1
kind: Service
metadata:
  name: server-grpc
spec:
  selector:
    app: server
  ports:
  - name: grpc
    port: 65000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: server-http
spec:
  selector:
    app: server
  ports:
  - name: http
    port: 8080
  type: ClusterIP
