name: build
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - run: make setup build

  check:
    runs-on: ubuntu-24.04
    needs: build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: golangci/golangci-lint-action@v8

  grpc-client-amd64:
    runs-on: ubuntu-24.04
    needs: check
    steps:
    - uses: actions/checkout@v4

    - uses: redhat-actions/buildah-build@v2
      id: build-grpc-client
      with:
        containerFiles: containers/client
        image: golang-grpc-client
        tags: latest-amd64

    - uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-grpc-client.outputs.image }}
        tags: ${{ steps.build-grpc-client.outputs.tags }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

  grpc-server-amd64:
    runs-on: ubuntu-24.04
    needs: check
    steps:
    - uses: actions/checkout@v4

    - uses: redhat-actions/buildah-build@v2
      id: build-grpc-server
      with:
        containerFiles: containers/server
        image: golang-grpc-server
        tags: latest-amd64

    - uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-grpc-server.outputs.image }}
        tags: ${{ steps.build-grpc-server.outputs.tags }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

  http-server-amd64:
    runs-on: ubuntu-24.04
    needs: check
    steps:
    - uses: actions/checkout@v4

    - uses: redhat-actions/buildah-build@v2
      id: build-http-server
      with:
        containerFiles: containers/http
        image: golang-http-server
        tags: latest-amd64

    - uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-http-server.outputs.image }}
        tags: ${{ steps.build-http-server.outputs.tags }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

  grpc-client-arm64:
    runs-on: ubuntu-24.04-arm
    needs: check
    steps:
    - uses: actions/checkout@v4

    - uses: redhat-actions/buildah-build@v2
      id: build-grpc-client
      with:
        containerFiles: containers/client
        image: golang-grpc-client
        tags: latest-arm64

    - uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-grpc-client.outputs.image }}
        tags: ${{ steps.build-grpc-client.outputs.tags }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

  grpc-server-arm64:
    runs-on: ubuntu-24.04-arm
    needs: check
    steps:
    - uses: actions/checkout@v4

    - uses: redhat-actions/buildah-build@v2
      id: build-grpc-server
      with:
        containerFiles: containers/server
        image: golang-grpc-server
        tags: latest-arm64

    - uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-grpc-server.outputs.image }}
        tags: ${{ steps.build-grpc-server.outputs.tags }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

  http-server-arm64:
    runs-on: ubuntu-24.04-arm
    needs: check
    steps:
    - uses: actions/checkout@v4

    - uses: redhat-actions/buildah-build@v2
      id: build-http-server
      with:
        containerFiles: containers/http
        image: golang-http-server
        tags: latest-arm64

    - uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-http-server.outputs.image }}
        tags: ${{ steps.build-http-server.outputs.tags }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
