name: build
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - run: make setup build check

  check:
    runs-on: ubuntu-24.04
    needs: build
    steps:
    - uses: golangci/golangci-lint-action@v8

  amd64:
    runs-on: ubuntu-24.04-arm
    needs: build
    steps:
    - uses: actions/checkout@v4

    - uses: redhat-actions/buildah-build@v2
      with:
        containerFiles: containers/client
        context: .
        image: golang-grpc-client
        platforms: linux/amd64
        push: true
        tags: latest-amd64

    - uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

  arm64:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - uses: redhat-actions/buildah-build@v2
      with:
        containerFiles: containers/client
        context: .
        image: golang-grpc-client
        platforms: linux/arm64
        push: true
        tags: latest-arm64

    - uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
