name: go
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24
    - uses: actions/cache@v2
      with:
        path: /go
        key: ${{ hashFiles('go.sum') }}
    - run: make setup build check

  podman:
    runs-on: ubuntu-latest
    needs: golang
    steps:
    - uses: actions/checkout@v4

    - uses: redhat-actions/buildah-build@v2
      with:
        containerFiles: containers/client
        context: .
        image: golang-grpc-client
        platforms: linux/amd64, linux/arm64
        push: true
        tags: latest ${{ github.sha }}

    - uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
